config/routes.rb
Rails.application.routes.draw do
  root 'theaters#index'

  resources :theaters, :only => [:index] do
    collection do
      get :search
      post :parse
    end
    resources :showtime_lists, :only => [:index], :path => 'showtimes'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/showtime_list.rb
class ShowtimeList < ApplicationRecord

  belongs_to :theater

  class << self

    def fetch(theater, date = Date.current)
      Fandango.theater_showtimes(
        :theater_id => theater.remote_id,
        :date       => date,
      )
    end

  end

  def refresh
    update!(
      :movies => self.class.fetch(theater, date)
    )
  end

  def stale?
    1.hour.ago > updated_at
  end

end

app/models/theater.rb
class Theater < ApplicationRecord

  has_many :showtime_lists do

    def for(date)
      showtime_list = find_or_initialize_by(
        :date => date,
      )
      showtime_list.refresh if showtime_list.new_record? || showtime_list.stale?
      showtime_list
    end

  private

    def theater
      proxy_association.owner
    end

  end

  class << self

    def search(zipcode)
      hashes = Fandango.movies_near(zipcode)

      hashes.map do |theater_hash|
        theater = Theater.find_or_initialize_by(
          :remote_id => theater_hash.fetch(:id),
        )

        unless theater.persisted?
          theater.attributes = {
            :name => theater_hash.fetch(:name),
          }
          theater.save!
        end

        theater
      end
    end

    def parse(parsed)
      parsed.fetch('theaters').map do |theater_hash|
        theater = create!(
          :name => theater_hash.fetch('name'),
          :remote_id => theater_hash.fetch('id'),
        )

        parse_showtime_list(theater, theater_hash)

        theater
      end
    end

  private

    def parse_showtime_list(theater, theater_hash)
      theater.showtime_lists.create!(
        :date   => Date.parse(theater_hash.fetch('displayDate')),
        :movies => parse_movies(theater_hash),
      )
    end

    def parse_movies(theater_hash)
      theater_hash.fetch('movies').map do |movie_hash|
        {
          :title => movie_hash.fetch('title'),
          :runtime => movie_hash.fetch('runtime'),
          :showtimes => movie_hash.fetch('variants').fetch(0).fetch('amenityGroups').fetch(0).fetch('showtimes').map do |showtime_hash|
            {
              :datetime => DateTime.parse(showtime_hash.fetch('ticketingDate')),
            }
          end,
        }
      end
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/showtime_lists_controller.rb
class ShowtimeListsController < ApplicationController

  def index
    @theater = Theater.find(params[:theater_id])
    @date =
      if params.key?(:date)
        Date.strptime(params[:date], '%m/%d/%Y')
      else
        Date.current
      end
    @showtime_list = @theater.showtime_lists.for(@date)
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController

  def index
  end

  def search
    @theaters = Theater.search(params[:zipcode])
  end

  def parse
    @theaters = Theater.parse(MultiJson.load(params[:json]))
    render :search
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title MovieMarathonRailsReact
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container-fluid
      = yield

app/views/showtime_lists/index.haml
= react_component('ShowtimeDates', 'date' => @date)

%hr

= react_component('App', 'movies' => @showtime_list.movies)

app/views/theaters/index.haml
= form_tag search_theaters_path, :method => :get do

  .form-group
    = text_field_tag :zipcode, nil, :placeholder => 'Enter Zipcode', :class => 'form-control'

  .form-group
    = submit_tag 'Search Theaters', :class => 'btn btn-info'

or

= form_tag parse_theaters_path do
  .form-group
    = text_area_tag :json, nil, :placeholder => 'JSON', :class => 'form-control'

  .form-group
    = submit_tag

app/views/theaters/search.haml
%ul
  - @theaters.each do |theater|
    %li
      = link_to theater.name, theater_showtime_lists_path(theater)